general.import = [
    # "~/.config/alacritty/gruvbox.toml"
    # "~/.config/alacritty/nord.toml"
    # "~/.config/alacritty/nord-dark.toml"
    # "~/.config/alacritty/grey.toml"
    "~/.config/alacritty/evening.toml"
]

[font]
size = 17.75
normal = { family = "IosevkaNerdFontMono", style = "Regular" }
bold = { family = "IosevkaNerdFontMono", style = "Bold" }
italic = { family = "IosevkaNerdFontMono", style = "Italic" }

[window]
dimensions = {columns = 100, lines = 35}
